const products = [
  {
    '_id': '1',
    'name': 'Airpods Wireless Bluetooth Headphones',
    'image': [
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MWP22_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1591634795000',
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MWP22?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1591634795000',
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MWP22_AV2?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1591634795000',
    ],
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 89.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
    'popular_course': true,
  },
  {
    '_id': '2',
    'name': 'iPhone 11 Pro 256GB Memory',
    'image': [
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone11pro-digitalmat-gallery-1-201909?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1567291164237',
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone11pro-digitalmat-gallery-2-201909?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1567291164768',
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone11pro-digitalmat-gallery-3-201909?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1567291165103',
    ],
    'description':
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 599.99,
    'countInStock': 0,
    'rating': 4.0,
    'numReviews': 8,
    'popular_course': true,
  },
  {
    '_id': '3',
    'name': 'Canon EOS 80D DSLR Camera',
    'image': [
      'https://cdn.mos.cms.futurecdn.net/qTij9sk5ctTA2ex3Ad3vJ9-320-80.jpg',
      'https://cdn.mos.cms.futurecdn.net/K4rc8ANADz9fnSHcxy7ZZA-320-80.jpg',
      'https://cdn.mos.cms.futurecdn.net/5SGzCQL5Sz5JvD9r56ApjZ-320-80.jpg',
    ],
    'description':
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    'brand': 'Canon',
    'category': 'Electronics',
    'price': 929.99,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
    'popular_course': true,
  },
  {
    '_id': '4',
    'name': 'Sony Playstation 4 Pro White Version',
    'image': [
      'https://m.media-amazon.com/images/I/71VKi8DR4sL._AC_SL1500_.jpg',
      'https://m.media-amazon.com/images/I/71FF29LOXfL._AC_SL1500_.jpg',
      'https://m.media-amazon.com/images/I/71vgVuq4QUL._AC_SL1500_.jpg',
    ],
    'description':
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    'brand': 'Sony',
    'category': 'Electronics',
    'price': 399.99,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
    'popular_course': true,
  },
  {
    '_id': '5',
    'name': 'Logitech G-Series Gaming Mouse',
    'image': [
      'https://resource.logitechg.com/d_transparent.gif/content/dam/gaming/en/products/g502-hero/g502-hero-gallery-1.png',
      'https://resource.logitechg.com/d_transparent.gif/content/dam/gaming/en/products/g502-hero/g502-hero-gallery-2.png',
      'https://resource.logitechg.com/d_transparent.gif/content/dam/gaming/en/products/g502-hero/g502-hero-gallery-3.png',
    ],
    'description':
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    'brand': 'Logitech',
    'category': 'Electronics',
    'price': 49.99,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
    'popular_course': true,
  },
  {
    '_id': '6',
    'name': 'Amazon Echo Dot 3rd Generation',
    'image': [
      'https://m.media-amazon.com/images/I/6182S7MYC2L._AC_SL1000_.jpg',
      'https://m.media-amazon.com/images/I/61u48FEs5TL._AC_SL1000_.jpg',
      'https://m.media-amazon.com/images/I/61VGI1I+esL._AC_SL1000_.jpg',
    ],
    'description':
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    'brand': 'Amazon',
    'category': 'Electronics',
    'price': 29.99,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
    'popular_course': true,
  },
  {
    '_id': '7',
    'name': 'Samsung Galaxy S21 Ultra',
    'image': [
      'https://image-us.samsung.com/SamsungUS/home/mobile/phones/galaxy-s/galaxy-s21-ultra-5g/buy/S21_Ultra_Phantom_Black_001_Front_MO.jpg',
      'https://image-us.samsung.com/SamsungUS/home/mobile/phones/galaxy-s/galaxy-s21-ultra-5g/buy/S21_Ultra_Phantom_Silver_001_Front_MO.jpg',
      'https://image-us.samsung.com/SamsungUS/home/mobile/phones/galaxy-s/galaxy-s21-ultra-5g/buy/S21_Ultra_Phantom_Black_001_Front_Open_MO.jpg',
    ],
    'description':
      'Samsung Galaxy S21 Ultra with 108MP camera, 5G support, and massive 5000mAh battery for extended use',
    'brand': 'Samsung',
    'category': 'Electronics',
    'price': 1199.99,
    'countInStock': 4,
    'rating': 4.8,
    'numReviews': 15,
    'popular_course': true,
  },
  {
    '_id': '8',
    'name': 'Dell XPS 13 Laptop',
    'image': [
      'https://i.dell.com/sites/csimages/Merchandizing_Imagery/all/xps-13-7390-laptop.jpg',
      'https://i.dell.com/sites/csimages/Merchandizing_Imagery/all/xps-13-7390-laptop-2.jpg',
      'https://i.dell.com/sites/csimages/Merchandizing_Imagery/all/xps-13-7390-laptop-3.jpg',
    ],
    'description':
      'Dell XPS 13 with Intel Core i7 processor, 16GB RAM, and 512GB SSD. Sleek design and powerful performance for professionals on the go',
    'brand': 'Dell',
    'category': 'Electronics',
    'price': 999.99,
    'countInStock': 6,
    'rating': 4.6,
    'numReviews': 20,
    'popular_course': true,
  },
  {
    '_id': '9',
    'name': 'Bose Noise Cancelling Headphones 700',
    'image': [
      'https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/headphones/noise_cancelling_headphones_700/product_silo_images/NC700_Ecom_Silver_LS_RGB-CC_d-min.jpg',
      'https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/headphones/noise_cancelling_headphones_700/product_silo_images/NC700_Ecom_Silver_RS_RGB-CC_d-min.jpg',
      'https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/headphones/noise_cancelling_headphones_700/product_silo_images/NC700_Ecom_Silver_TD_RGB-CC_d-min.jpg',
    ],
    'description':
      'Bose Noise Cancelling Headphones 700 deliver everything you expect—and things you never imagined possible. Powerful noise cancelling, astonishing sound, unrivaled voice pickup',
    'brand': 'Bose',
    'category': 'Electronics',
    'price': 379.99,
    'countInStock': 9,
    'rating': 4.7,
    'numReviews': 25,
    'popular_course': true,
  },
  {
    '_id': '10',
    'name': 'GoPro HERO9 Black',
    'image': [
      'https://gopro.com/content/dam/gopro/en-na/products/cameras/hero9-black/hero9-black-5-Front.png',
      'https://gopro.com/content/dam/gopro/en-na/products/cameras/hero9-black/hero9-black-1.png',
      'https://gopro.com/content/dam/gopro/en-na/products/cameras/hero9-black/hero9-black-2.png',
    ],
    'description':
      'GoPro HERO9 Black - More power. More clarity. More stability. Featuring a new front display, 30% more battery life, and hyper smooth stabilization 3.0',
    'brand': 'GoPro',
    'category': 'Electronics',
    'price': 449.99,
    'countInStock': 8,
    'rating': 4.9,
    'numReviews': 30,
    'popular_course': true,
  },
  {
    '_id': '11',
    'name': 'Apple MacBook Pro 16-inch',
    'image': [
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/refurb-mbp16touch-space-gallery-2022?wid=572&hei=572&fmt=jpeg&qlt=95&.v=1646693159000',
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/refurb-mbp16touch-space-gallery-2022_AV1?wid=572&hei=572&fmt=jpeg&qlt=95&.v=1646693158000',
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/refurb-mbp16touch-space-gallery-2022_AV2?wid=572&hei=572&fmt=jpeg&qlt=95&.v=1646693156000',
    ],
    'description':
      'Apple MacBook Pro 16-inch with M1 Pro chip, 16GB RAM, and 1TB SSD. Ultimate performance for creative professionals',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 2499.99,
    'countInStock': 3,
    'rating': 4.8,
    'numReviews': 18,
    'popular_course': true,
  },
  {
    '_id': '12',
    'name': 'Sony WH-1000XM4 Wireless Noise-Canceling Headphones',
    'image': [
      'https://m.media-amazon.com/images/I/71o8Q5XJS5L._AC_SL1500_.jpg',
      'https://m.media-amazon.com/images/I/71WyJ1AaB4L._AC_SL1500_.jpg',
      'https://m.media-amazon.com/images/I/71TPda7cwUL._AC_SL1500_.jpg',
    ],
    'description':
      'Sony WH-1000XM4 Wireless Noise-Canceling Headphones with industry-leading noise cancellation, exceptional sound quality, and smart listening features',
    'brand': 'Sony',
    'category': 'Electronics',
    'price': 349.99,
    'countInStock': 7,
    'rating': 4.9,
    'numReviews': 22,
    'popular_course': true,
  },
  {
    '_id': '13',
    'name': 'HP Envy 13 Laptop',
    'image': [
      'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06837813.png',
      'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06837812.png',
      'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06837811.png',
    ],
    'description':
      'HP Envy 13 Laptop with Intel Core i5 processor, 8GB RAM, and 256GB SSD. Lightweight and powerful with stunning visuals',
    'brand': 'HP',
    'category': 'Electronics',
    'price': 799.99,
    'countInStock': 12,
    'rating': 4.3,
    'numReviews': 16,
    'popular_course': true,
  },
  {
    '_id': '14',
    'name': 'Microsoft Surface Pro 7',
    'image': [
      'https://m.media-amazon.com/images/I/71xN89J7A8L._AC_SL1500_.jpg',
      'https://m.media-amazon.com/images/I/61m2NgtDa8L._AC_SL1500_.jpg',
      'https://m.media-amazon.com/images/I/71pY+N9TOQL._AC_SL1500_.jpg',
    ],
    'description':
      'Microsoft Surface Pro 7 with Intel Core i7, 16GB RAM, and 512GB SSD. Versatile 2-in-1 laptop with a touch screen and detachable keyboard',
    'brand': 'Microsoft',
    'category': 'Electronics',
    'price': 1399.99,
    'countInStock': 5,
    'rating': 4.7,
    'numReviews': 19,
    'popular_course': true,
  },
  {
    '_id': '15',
    'name': 'Nikon D3500 DSLR Camera',
    'image': [
      'https://cdn.mos.cms.futurecdn.net/2e8tVsMNk4W8hJmYYLMm7M-970-80.jpg',
      'https://cdn.mos.cms.futurecdn.net/WGX9ugzSReT3q6cXa2QnpX-970-80.jpg',
      'https://cdn.mos.cms.futurecdn.net/ZHTy3YXSC3MULKPzwdt3i9-970-80.jpg',
    ],
    'description':
      'Nikon D3500 DSLR Camera with 24.2MP sensor, full HD video recording, and easy-to-use interface. Perfect for beginners and enthusiasts',
    'brand': 'Nikon',
    'category': 'Electronics',
    'price': 499.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 14,
    'popular_course': true,
  },
  {
    '_id': '16',
    'name': 'Apple Watch Series 6',
    'image': [
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MYWU2_VW_34FR+watch-40-alum-silver-nc-6s_VW_34FR_WF_CO_GEO_US?wid=940&hei=1112&fmt=png-alpha&.v=1599936777000',
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MYWU2_VW_34FR+watch-40-alum-silver-nc-6s_VW_34FR_WF_CO_GEO_US?wid=940&hei=1112&fmt=png-alpha&.v=1599936777000',
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MYWU2_VW_34FR+watch-40-alum-silver-nc-6s_VW_34FR_WF_CO_GEO_US?wid=940&hei=1112&fmt=png-alpha&.v=1599936777000',
    ],
    'description':
      'Apple Watch Series 6 with blood oxygen sensor, ECG app, and always-on Retina display. The ultimate device for a healthy life',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 399.99,
    'countInStock': 15,
    'rating': 4.9,
    'numReviews': 25,
    'popular_course': true,
  },
  {
    '_id': '17',
    'name': 'Fitbit Charge 4 Fitness and Activity Tracker',
    'image': [
      'https://m.media-amazon.com/images/I/71smqRr0pmL._AC_SL1500_.jpg',
      'https://m.media-amazon.com/images/I/61BZRU8kMtL._AC_SL1500_.jpg',
      'https://m.media-amazon.com/images/I/51nAFdvRwdL._AC_SL1500_.jpg',
    ],
    'description':
      'Fitbit Charge 4 with built-in GPS, heart rate tracking, and sleep monitoring. Stay fit and healthy with advanced fitness tracking features',
    'brand': 'Fitbit',
    'category': 'Electronics',
    'price': 149.99,
    'countInStock': 20,
    'rating': 4.6,
    'numReviews': 30,
    'popular_course': true,
  },
  {
    '_id': '18',
    'name': 'JBL Flip 5 Portable Bluetooth Speaker',
    'image': [
      'https://m.media-amazon.com/images/I/81FLh18tkRL._AC_SL1500_.jpg',
      'https://m.media-amazon.com/images/I/81WcvKWMhDL._AC_SL1500_.jpg',
      'https://m.media-amazon.com/images/I/81Zt42ioCgL._AC_SL1500_.jpg',
    ],
    'description':
      'JBL Flip 5 with powerful sound, waterproof design, and up to 12 hours of playtime. Perfect for outdoor adventures and parties',
    'brand': 'JBL',
    'category': 'Electronics',
    'price': 119.99,
    'countInStock': 18,
    'rating': 4.8,
    'numReviews': 35,
    'popular_course': true,
  },
];

export default products;
